#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-education-data
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

scheduler:
  import-susa-json:
    cron: ${ENV_SCHEDULER_JSON_IMPORT_CRON}
    name: "scheduled-json-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  import-categories:
    cron: ${ENV_SCHEDULER_CATEGORIES_IMPORT_CRON}
    name: "scheduled-categories-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  create-entities:
    cron: ${ENV_SCHEDULER_ENTITIES_CREATION_CRON}
    name: "scheduled-entities-creation"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
    municipality-whitelist: 2281

integration:
  planned-education:
    base-url: ${ENV_PLANNED_EDUCATION_BASE_URL}
  susa-navet:
    base-url: ${ENV_SUSA_NAVET_BASE_URL}