#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-education-data
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

integration:
  planned-education:
    base-url: ${ENV_PLANNED_EDUCATION_BASE_URL}
  susa-navet:
    base-url: ${ENV_SUSA_NAVET_BASE_URL}