#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-education-data
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
scheduler:
  import:
    cron: "0 */1 * * * *"
    name: "scheduled-import"
    shedlock-lock-at-most-for: "PT2H"
    maximum-execution-time: "PT2H"

scheduler:
  import:
    cron: "0 0 2 * * *"
    name: "scheduled-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
    json-size: 100

integration:
  planned-education:
    base-url: ${ENV_PLANNED_EDUCATION_BASE_URL}
  susa-navet:
    base-url: ${ENV_SUSA_NAVET_BASE_URL}