#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    url: jdbc:tc:mariadb:10.6:///
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

scheduler:
  import-susa-json:
    cron: "-"
    name: "scheduled-json-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  import-categories:
    cron: "-"
    name: "scheduled-categories-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  create-entities:
    cron: "-"
    name: "scheduled-entities-creation"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  refresh-category-relations:
    cron: "-"
    name: "scheduled-refresh-category-relations"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"

municipality-whitelist: 2281

integration:
  planned-education:
    base-url: ${wiremock.server.baseUrl}/planned-educations
  susa-navet:
    base-url: ${wiremock.server.baseUrl}/susa-navet/emil3