#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    url: jdbc:tc:mariadb:10.6:///
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

scheduler:
  import-susa-json:
    cron: "0 0 2 * * *"
    name: "scheduled-json-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
    json-size: 100
  import-categories:
    cron: "0 0 3 * * *"
    name: "scheduled-categories-import"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
  generate:
    cron: "0 0 4 * * *"
    name: "scheduled-generation"
    shedlock-lock-at-most-for: "PT15M"
    maximum-execution-time: "PT15M"
    municipality-whitelist: 2281

integration:
  planned-education:
    base-url: ${wiremock.server.baseUrl}/planned-educations
  susa-navet:
    base-url: ${wiremock.server.baseUrl}/susa-navet/emil3